### ISSUE TITLE
继承这个BaseToolBarActivity非要用LinearLayout，好坑

### ISSUE THREAD

**Issue by xfy-c** [ldlywt/FastJetpack#15]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fastjetpack/com.aisier.ui.MainActivity}: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.RelativeLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3455)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3598)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2164)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:944)
     Caused by: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.RelativeLayout
        at com.aisier.databinding.ActivityMainBinding.bind(ActivityMainBinding.java:74)
        at com.aisier.ui.MainActivity$special$$inlined$viewBindingActivity$default$1.invoke(ActivityViewBindings.kt:66)
        at com.aisier.ui.MainActivity$special$$inlined$viewBindingActivity$default$1.invoke(Unknown Source:2)
        at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:75)
        at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:62)
        at com.aisier.ui.MainActivity.getMBinding(MainActivity.kt:11)
        at com.aisier.ui.MainActivity.init(MainActivity.kt:13)
        at com.aisier.architecture.base.BaseToolBarActivity.onCreate(BaseToolBarActivity.kt:18)
        at android.app.Activity.performCreate(Activity.java:7822)
        at android.app.Activity.performCreate(Activity.java:7811)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1328)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3598) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2164) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:241) 
        at android.app.ActivityThread.main(ActivityThread.java:7582) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:944)

**Comment by ldlywt** [comment]
我把这个删了，囧
